module.exports.errors = {
  "ERR_UNKNOWN":{"error": "internal_error","error_description": "May be an hamster bite a wire" },
  "ERR_NO_RESPONSE_WHEN_CREATE":{"error": "internal_error","error_description": "No response when create" },
  "ERR_WHEN_CREATE":{"error": "internal_error","error_description": "Error when create" },
  "ERR_WHEN_RETRIEVING":{"error": "internal_error","error_description": "Internal error when retrieving data" },
  "ERR_WHEN_EXECUTE":{"error": "internal_error","error_description": "Internal error when retrieving data" },
  "NOT_FOUND":{"error": "not_found","error_description": "No ressource found" },
  "ERR_WITH_DATABASE":{"error": "internal_error","error_description": "Internal problem with database" },
  "CONFLICT":{"error": "ressource_version_conflict","error_description": "Ressource already exist"},
  "ERR_WHEN_DELETE":{"error": "internal_error","error_description": "Internal error while deleting"},
  "ERR_NO_INDEX":{"error": "error_no_index","error_description": "index not found, wrong url?"}
};
